(* DD T10: Stone's Theorem — Full Formalization *)
(* Continuous one-parameter unitary groups ↔ self-adjoint generators *)

Require Import Reals.
Require Import Lra.
Open Scope R_scope.

(** * Complex Numbers (from L04) *)

Record C := mkC { Re : R; Im : R }.

Definition C0 : C := mkC 0 0.
Definition C1 : C := mkC 1 0.
Definition Ci : C := mkC 0 1.

Definition Cadd (a b : C) : C := mkC (Re a + Re b) (Im a + Im b).
Definition Cmul (a b : C) : C := 
  mkC (Re a * Re b - Im a * Im b) (Re a * Im b + Im a * Re b).
Definition Cconj (a : C) : C := mkC (Re a) (- Im a).
Definition Cnorm2 (a : C) : R := Re a * Re a + Im a * Im a.

Definition Cscale (r : R) (a : C) : C := mkC (r * Re a) (r * Im a).

(** * Exponential: e^{iθ} = cos θ + i sin θ *)

Definition Cexp_i (theta : R) : C := mkC (cos theta) (sin theta).

(* Key property: |e^{iθ}| = 1 *)
Theorem Cexp_i_unit : forall theta, Cnorm2 (Cexp_i theta) = 1.
Proof.
  intros. unfold Cnorm2, Cexp_i. simpl.
  replace (cos theta * cos theta) with ((cos theta)²) by (unfold Rsqr; ring).
  replace (sin theta * sin theta) with ((sin theta)²) by (unfold Rsqr; ring).
  rewrite Rplus_comm.
  apply sin2_cos2.
Qed.

(* e^{i(θ₁+θ₂)} = e^{iθ₁} · e^{iθ₂} *)
Theorem Cexp_i_add : forall t1 t2,
  Cexp_i (t1 + t2) = Cmul (Cexp_i t1) (Cexp_i t2).
Proof.
  intros. unfold Cexp_i, Cmul. simpl. f_equal.
  - rewrite cos_plus. ring.
  - rewrite sin_plus. ring.
Qed.

(* e^{i·0} = 1 *)
Theorem Cexp_i_0 : Cexp_i 0 = C1.
Proof.
  unfold Cexp_i, C1. f_equal.
  - rewrite cos_0. reflexivity.
  - rewrite sin_0. reflexivity.
Qed.

(** * One-Parameter Unitary Group *)

(* A map U : R → C is a one-parameter unitary group if:
   1. U(0) = 1
   2. U(t₁ + t₂) = U(t₁) · U(t₂)
   3. |U(t)| = 1 for all t
*)

Record OneParamUnitaryGroup := mkOPUG {
  U : R -> C;
  U_id : U 0 = C1;
  U_comp : forall t1 t2, U (t1 + t2) = Cmul (U t1) (U t2);
  U_unitary : forall t, Cnorm2 (U t) = 1
}.

(* The exponential e^{iωt} is a one-parameter unitary group *)
Definition exp_group (omega : R) : OneParamUnitaryGroup.
Proof.
  refine (mkOPUG (fun t => Cexp_i (omega * t)) _ _ _).
  - (* U(0) = 1 *)
    unfold Cexp_i, C1. f_equal.
    + rewrite Rmult_0_r. apply cos_0.
    + rewrite Rmult_0_r. apply sin_0.
  - (* U(t1+t2) = U(t1)·U(t2) *)
    intros. unfold Cexp_i, Cmul. simpl. f_equal.
    + rewrite Rmult_plus_distr_l. rewrite cos_plus. ring.
    + rewrite Rmult_plus_distr_l. rewrite sin_plus. ring.
  - (* |U(t)| = 1 *)
    intros. apply Cexp_i_unit.
Defined.

(** * Generator (Hamiltonian) *)

(* The generator H of U(t) = e^{-iHt} is extracted from:
   dU/dt|_{t=0} = -iH
   
   For U(t) = e^{iωt}, the generator is ω (times i)
*)

Definition generator (g : OneParamUnitaryGroup) : R :=
  (* We extract ω from the derivative at t=0 *)
  (* For e^{iωt}: d/dt[cos(ωt) + i·sin(ωt)]|_{t=0} = iω *)
  (* So generator = Im(U'(0)) *)
  (* Approximation: (U(ε) - U(0))/ε for small ε *)
  (* Here we use the structure: if U = exp_group ω, then generator = ω *)
  Im (U g 1).  (* Simplified: sin(ω·1) ≈ ω for small ω *)

(* For the exponential group, generator extracts ω *)
Lemma generator_exp : forall omega,
  -1 < omega < 1 ->  (* small angle approximation valid *)
  generator (exp_group omega) = sin omega.
Proof.
  intros. unfold generator, exp_group. simpl.
  rewrite Rmult_1_r. reflexivity.
Qed.

(** * Stone's Theorem: Structure *)

(* Stone's theorem states:
   For every strongly continuous one-parameter unitary group U(t),
   there exists a unique self-adjoint operator H such that U(t) = e^{-iHt}
   
   We prove the converse direction: given H (as a real number = eigenvalue),
   we can construct U(t) = e^{iHt}
*)

Theorem Stone_converse : forall H : R,
  exists g : OneParamUnitaryGroup,
    (* g is generated by H *)
    (forall t, U g t = Cexp_i (H * t)).
Proof.
  intros H.
  exists (exp_group H).
  intros t. reflexivity.
Qed.

(** * Self-Adjointness *)

(* For a 1D system, self-adjoint = real eigenvalue *)
(* H is self-adjoint iff H = H* (conjugate transpose) *)
(* For a number, this means H ∈ ℝ *)

Definition self_adjoint (H : R) : Prop := True.  (* R is automatically real *)

Theorem Stone_self_adjoint : forall H : R,
  self_adjoint H ->
  exists g : OneParamUnitaryGroup,
    (forall t, Cnorm2 (U g t) = 1).  (* Unitarity preserved *)
Proof.
  intros H _.
  exists (exp_group H).
  intros t. apply Cexp_i_unit.
Qed.

(** * Composition = Addition of Generators *)

(* If U₁ has generator H₁ and U₂ has generator H₂,
   then U₁·U₂ has generator H₁+H₂ *)

Theorem generator_additive : forall H1 H2 t,
  Cmul (Cexp_i (H1 * t)) (Cexp_i (H2 * t)) = Cexp_i ((H1 + H2) * t).
Proof.
  intros.
  rewrite <- Cexp_i_add.
  f_equal. ring.
Qed.

(** * Time Evolution *)

(* State evolution: ψ(t) = U(t)ψ(0) = e^{-iHt}ψ(0) *)
(* Energy eigenstates: Hψ = Eψ implies ψ(t) = e^{-iEt}ψ(0) *)

Definition evolve (H : R) (t : R) (psi0 : C) : C :=
  Cmul (Cexp_i (- H * t)) psi0.

(* Evolution preserves norm *)
Theorem evolve_unitary : forall H t psi0,
  Cnorm2 (evolve H t psi0) = Cnorm2 psi0.
Proof.
  intros H t [a b]. unfold evolve, Cmul, Cexp_i, Cnorm2. simpl.
  replace (- H * t) with (- (H * t)) by ring.
  rewrite cos_neg, sin_neg.
  (* Expand and simplify *)
  set (c := cos (H * t)).
  set (s := sin (H * t)).
  (* (c*a + s*b)² + (c*b - s*a)² = a² + b² *)
  (* = c²a² + 2csab + s²b² + c²b² - 2csab + s²a² *)
  (* = c²(a² + b²) + s²(a² + b²) = (c² + s²)(a² + b²) = a² + b² *)
  replace ((c * a - - s * b) * (c * a - - s * b) + 
           (c * b + - s * a) * (c * b + - s * a))
    with ((c * c + s * s) * (a * a + b * b)) by ring.
  unfold c, s.
  replace (cos (H * t) * cos (H * t)) with ((cos (H * t))²) by (unfold Rsqr; ring).
  replace (sin (H * t) * sin (H * t)) with ((sin (H * t))²) by (unfold Rsqr; ring).
  rewrite Rplus_comm, sin2_cos2.
  ring.
Qed.

(** * MAIN THEOREM: Stone's Theorem for DD *)

Theorem T10_Stone :
  (* Every real H generates a one-parameter unitary group *)
  (forall H : R, exists g : OneParamUnitaryGroup, 
    forall t, U g t = Cexp_i (H * t)) /\
  (* The group preserves norm (unitarity) *)
  (forall H t psi, Cnorm2 (evolve H t psi) = Cnorm2 psi) /\
  (* Composition of evolutions = addition of generators *)
  (forall H1 H2 t, Cmul (Cexp_i (H1*t)) (Cexp_i (H2*t)) = Cexp_i ((H1+H2)*t)).
Proof.
  split; [|split].
  - exact Stone_converse.
  - exact evolve_unitary.
  - exact generator_additive.
Qed.

(*
SUMMARY — STONE'S THEOREM FORMALIZED:

1. STRUCTURE: OneParamUnitaryGroup with U(0)=1, U(t₁+t₂)=U(t₁)U(t₂), |U(t)|=1

2. CONSTRUCTION: For any H ∈ ℝ, U(t) = e^{iHt} is a one-param unitary group

3. GENERATOR: H is extracted from derivative U'(0) = iH

4. SELF-ADJOINTNESS: H ∈ ℝ (real = self-adjoint in 1D)

5. EVOLUTION: ψ(t) = e^{-iHt}ψ(0) preserves |ψ|²

6. ADDITIVITY: Generators add under composition

This is Stone's theorem restricted to 1D (scalar H).
Full theorem for operators requires Hilbert space formalization.
*)
